### ISSUE TITLE
Files not submitted

### ISSUE THREAD

**Issue by crschriever** [nordicway/moji#12]
I'm using the QuickStart script. Whenever I run it, I get a print out for each file being uploaded but when I follow the link to check the results, this is what I see: `Options -l java -d -m 9999999`. This makes me think that the files aren't actually being uploaded. Shouldn't each of the files show up in a list after the -d?

**Comment by nordicway** [comment]
Hi!
The -d option just means "directory mode". There should be no files listed there.

Please make sure to stick to the setup that is explained in the README.
To double check against a well-known set of files, you may checkout this [Plagiarism detection test set](https://github.com/nordicway/SourceCode-Plagiarism-TestSets) and run the QuickStart with the "MiniFactorial" directory.
The MOSS result page should show some matches for that test set.

**Comment by nordicway** [comment]
closed due to inactivity
